//go:build windows

// Code generated by 'go generate' using "github.com/Microsoft/go-winio/tools/mkwinsyscall"; DO NOT EDIT.

package kernel

import (
	"syscall"
	"unsafe"

	"github.com/Microsoft/go-winio/internal/wintype"
	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modkernel32 = windows.NewLazySystemDLL("kernel32.dll")

	procCloseHandle   = modkernel32.NewProc("CloseHandle")
	procGlobalAlloc   = modkernel32.NewProc("GlobalAlloc")
	procGlobalFree    = modkernel32.NewProc("GlobalFree")
	procGlobalHandle  = modkernel32.NewProc("GlobalHandle")
	procGlobalLock    = modkernel32.NewProc("GlobalLock")
	procGlobalReAlloc = modkernel32.NewProc("GlobalReAlloc")
	procGlobalUnlock  = modkernel32.NewProc("GlobalUnlock")
	procLocalAlloc    = modkernel32.NewProc("LocalAlloc")
	procLocalFree     = modkernel32.NewProc("LocalFree")
	procLocalHandle   = modkernel32.NewProc("LocalHandle")
	procLocalLock     = modkernel32.NewProc("LocalLock")
	procLocalReAlloc  = modkernel32.NewProc("LocalReAlloc")
	procLocalUnlock   = modkernel32.NewProc("LocalUnlock")
)

func CloseHandle(h wintype.Handle) (ok bool, err error) {
	r0, _, e1 := syscall.Syscall(procCloseHandle.Addr(), 1, uintptr(h), 0, 0)
	ok = r0 != 0
	if !ok {
		err = errnoErr(e1)
	}
	return
}

func GlobalAlloc(flags wintype.UInt, bytes wintype.SizeT) (mem wintype.HGlobal, err error) {
	r0, _, e1 := syscall.Syscall(procGlobalAlloc.Addr(), 2, uintptr(flags), uintptr(bytes), 0)
	mem = wintype.HGlobal(r0)
	if mem == 0 {
		err = errnoErr(e1)
	}
	return
}

func GlobalFree(hMem wintype.HGlobal) (mem wintype.HGlobal, err error) {
	r0, _, e1 := syscall.Syscall(procGlobalFree.Addr(), 1, uintptr(hMem), 0, 0)
	mem = wintype.HGlobal(r0)
	if mem != 0 {
		err = errnoErr(e1)
	}
	return
}

func GlobalHandle(pMem wintype.LPCVoid) (hMem wintype.HGlobal, err error) {
	r0, _, e1 := syscall.Syscall(procGlobalHandle.Addr(), 1, uintptr(pMem), 0, 0)
	hMem = wintype.HGlobal(r0)
	if hMem == 0 {
		err = errnoErr(e1)
	}
	return
}

func GlobalLock(hMem wintype.HGlobal) (pMem wintype.LPVoid, err error) {
	r0, _, e1 := syscall.Syscall(procGlobalLock.Addr(), 1, uintptr(hMem), 0, 0)
	pMem = wintype.LPVoid(r0)
	if pMem == 0 {
		err = errnoErr(e1)
	}
	return
}

func GlobalReAlloc(hMem wintype.HGlobal, bytes wintype.SizeT, flags wintype.UInt) (mem wintype.HGlobal, err error) {
	r0, _, e1 := syscall.Syscall(procGlobalReAlloc.Addr(), 3, uintptr(hMem), uintptr(bytes), uintptr(flags))
	mem = wintype.HGlobal(r0)
	if mem == 0 {
		err = errnoErr(e1)
	}
	return
}

func GlobalUnlock(hMem wintype.HGlobal) (ok bool, err error) {
	r0, _, e1 := syscall.Syscall(procGlobalUnlock.Addr(), 1, uintptr(hMem), 0, 0)
	ok = r0 != 0
	if !ok {
		err = errnoErr(e1)
	}
	return
}

func LocalAlloc(flags wintype.UInt, bytes wintype.SizeT) (mem wintype.HLocal, err error) {
	r0, _, e1 := syscall.Syscall(procLocalAlloc.Addr(), 2, uintptr(flags), uintptr(bytes), 0)
	mem = wintype.HLocal(r0)
	if mem == 0 {
		err = errnoErr(e1)
	}
	return
}

func LocalFree(hMem wintype.HLocal) (mem wintype.HLocal, err error) {
	r0, _, e1 := syscall.Syscall(procLocalFree.Addr(), 1, uintptr(hMem), 0, 0)
	mem = wintype.HLocal(r0)
	if mem != 0 {
		err = errnoErr(e1)
	}
	return
}

func LocalHandle(pMem wintype.LPCVoid) (hMem wintype.HLocal, err error) {
	r0, _, e1 := syscall.Syscall(procLocalHandle.Addr(), 1, uintptr(pMem), 0, 0)
	hMem = wintype.HLocal(r0)
	if hMem == 0 {
		err = errnoErr(e1)
	}
	return
}

func LocalLock(hMem wintype.HLocal) (pMem wintype.LPVoid, err error) {
	r0, _, e1 := syscall.Syscall(procLocalLock.Addr(), 1, uintptr(hMem), 0, 0)
	pMem = wintype.LPVoid(r0)
	if pMem == 0 {
		err = errnoErr(e1)
	}
	return
}

func LocalReAlloc(hMem wintype.HLocal, bytes wintype.SizeT, flags wintype.UInt) (mem wintype.HLocal, err error) {
	r0, _, e1 := syscall.Syscall(procLocalReAlloc.Addr(), 3, uintptr(hMem), uintptr(bytes), uintptr(flags))
	mem = wintype.HLocal(r0)
	if mem == 0 {
		err = errnoErr(e1)
	}
	return
}

func LocalUnlock(hMem wintype.HLocal) (ok bool, err error) {
	r0, _, e1 := syscall.Syscall(procLocalUnlock.Addr(), 1, uintptr(hMem), 0, 0)
	ok = r0 != 0
	if !ok {
		err = errnoErr(e1)
	}
	return
}
